### ISSUE TITLE
Unable to use EE in AWX 19.0

### ISSUE THREAD

**Issue by callumbnz** [ansible/network-ee#42]
Have specified quay.io/ansible/network-ee:stable-2.9 as the EE image (have also tried :latest, :2.10-stable) and get the below error when trying to execute a job in AWX.

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1397, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2957, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3008, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Error creating pod: container failed with exit code 1:

**Comment by pabelanger** [comment]
@callumbnz Right now, we are only uses these images in our CI pipelines so it is possible they won't work as expected in AWX. That said, it would be interesting to debug awx to better understand more.

**Comment by shanemcd** [comment]
Thanks for opening this issue. I should have realized that people would want to do this. Right now, the default awx-ee does this: https://github.com/ansible/awx-ee/blob/devel/Containerfile#L28-L29

We will spend some time thinking through how to make EEs more universally functional.
